// ═══════════════════════════════════════════════════════════════════════════
// TFM TinyML Detector — main.cpp
//
// Entry point for the ESP32-S3 TinyML object detection firmware.
// Orchestrates: camera → preprocess → inference → postprocess → metrics → WS
//
// Architecture:
//   Core 0 — Inference task  (capture + infer + postprocess)
//   Core 1 — WiFi + HTTP/WS  (managed by ESP-IDF)
//
// Model selection at compile time via ACTIVE_MODEL_TYPE / ACTIVE_ENGINE_TYPE
// or at runtime via WebSocket command.
// ═══════════════════════════════════════════════════════════════════════════
#include "app_config.h"
#include "camera.h"
#include "image_proc.h"
#include "inference_engine.h"
#include "tflite_engine.h"
#include "espdl_engine.h"
#include "postprocess.h"
#include "metrics.h"
#include "wifi_manager.h"
#include "web_server.h"

#include "esp_log.h"
#include "esp_system.h"
#include "esp_heap_caps.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include <cstdio>
#include <memory>

static const char* TAG = "main";

// ═══════════════════════════════════════════════════════════════════════════
//  Model data (TFLite C arrays — generated by xxd)
// ═══════════════════════════════════════════════════════════════════════════
#include "models/tflite/mobilenetv2_ssdlite_v1_int8.h"
#include "models/tflite/yolo11n_v1_int8.h"
#include "models/tflite/yolo26n_v1_int8.h"

// ─── ESP-DL embedded binaries (linked via EMBED_FILES in CMakeLists) ─────
#if __has_include("espdl_model_list.h")
// Will be populated when .espdl models are available
extern const uint8_t mobilenetv2_ssdlite_v1_espdl_start[] asm("_binary_mobilenetv2_ssdlite_v1_espdl_start");
extern const uint8_t mobilenetv2_ssdlite_v1_espdl_end[]   asm("_binary_mobilenetv2_ssdlite_v1_espdl_end");
extern const uint8_t yolo11n_v1_espdl_start[]              asm("_binary_yolo11n_v1_espdl_start");
extern const uint8_t yolo11n_v1_espdl_end[]                asm("_binary_yolo11n_v1_espdl_end");
extern const uint8_t yolo26n_v1_espdl_start[]              asm("_binary_yolo26n_v1_espdl_start");
extern const uint8_t yolo26n_v1_espdl_end[]                asm("_binary_yolo26n_v1_espdl_end");
#define HAS_ESPDL_MODELS 1
#else
#define HAS_ESPDL_MODELS 0
#endif

// ═══════════════════════════════════════════════════════════════════════════
//  Compile-time model selection  (override via sdkconfig / menuconfig)
// ═══════════════════════════════════════════════════════════════════════════
#ifndef ACTIVE_MODEL_TYPE
#define ACTIVE_MODEL_TYPE   ModelType::YOLO11N
#endif

#ifndef ACTIVE_ENGINE_TYPE
#define ACTIVE_ENGINE_TYPE  EngineType::TFLITE_MICRO
#endif

// ═══════════════════════════════════════════════════════════════════════════
//  Model configurations
// ═══════════════════════════════════════════════════════════════════════════
static ModelConfig make_model_config(ModelType type, EngineType engine) {
    ModelConfig cfg{};
    cfg.type   = type;
    cfg.engine = engine;

    switch (type) {
    case ModelType::MOBILENET_SSD:
        cfg.name         = "MBNTv2_ssdlite_v1";
        cfg.tflite_data  = mobilenetv2_ssdlite_v1_int8_tflite;
        cfg.tflite_size  = mobilenetv2_ssdlite_v1_int8_tflite_len;
        cfg.arena_size   = 1260680 * 3;   // ~3.6 MB
        cfg.conf_threshold = 0.30f;       // SSD needs slightly higher
        break;

    case ModelType::YOLO11N:
        cfg.name         = "YOLO11n_v1";
        cfg.tflite_data  = yolo11n_v1_int8_tflite;
        cfg.tflite_size  = yolo11n_v1_int8_tflite_len;
        cfg.arena_size   = 2812554 * 3;   // ~8.0 MB
        break;

    case ModelType::YOLO26N:
        cfg.name         = "YOLO26n_v1";
        cfg.tflite_data  = yolo26n_v1_int8_tflite;
        cfg.tflite_size  = yolo26n_v1_int8_tflite_len;
        cfg.arena_size   = 2677201 * 3;   // ~7.6 MB
        break;
    }

    return cfg;
}

// ═══════════════════════════════════════════════════════════════════════════
//  Inference engine factory
// ═══════════════════════════════════════════════════════════════════════════
static InferenceEngine* create_engine(EngineType type) {
    switch (type) {
    case EngineType::TFLITE_MICRO:
        return new TFLiteEngine();
    case EngineType::ESP_DL:
        return new EspDlEngine();
    }
    return nullptr;
}

// ═══════════════════════════════════════════════════════════════════════════
//  Postprocess dispatcher
// ═══════════════════════════════════════════════════════════════════════════
static DetectionResult run_postprocess(const InferenceEngine* engine,
                                       const ModelConfig& cfg)
{
    // For TFLite output — floats are already dequantized
    switch (cfg.type) {
    case ModelType::MOBILENET_SSD: {
        // 3 output tensors: [0]=(1,1470,4) box, [1]=(1,1470,5) cls, [2]=(1,1470,1) obj
        // Note: output order from TFLite may vary — we identify by shape
        const float* out0 = static_cast<const float*>(engine->get_output(0));
        const float* out1 = static_cast<const float*>(engine->get_output(1));
        const float* out2 = static_cast<const float*>(engine->get_output(2));

        // Identify which output is which by checking dimensions
        int dims0[4], dims1[4], dims2[4];
        int nd0, nd1, nd2;
        engine->get_output_shape(0, dims0, &nd0);
        engine->get_output_shape(1, dims1, &nd1);
        engine->get_output_shape(2, dims2, &nd2);

        // Assign by last dimension: 4=box, 5=cls, 1=obj
        const float* objectness   = nullptr;
        const float* class_probs  = nullptr;
        const float* bbox_preds   = nullptr;

        auto assign = [&](const float* ptr, int last_dim) {
            if (last_dim == 1)              objectness  = ptr;
            else if (last_dim == NUM_CLASSES) class_probs = ptr;
            else if (last_dim == 4)          bbox_preds  = ptr;
        };

        assign(out0, dims0[nd0 - 1]);
        assign(out1, dims1[nd1 - 1]);
        assign(out2, dims2[nd2 - 1]);

        if (objectness && class_probs && bbox_preds) {
            return postprocess_mobilenet(objectness, class_probs, bbox_preds,
                                         cfg.conf_threshold, cfg.iou_threshold);
        }
        ESP_LOGE(TAG, "No se pudieron identificar los tensores de salida MBNTv2");
        return DetectionResult{};
    }

    case ModelType::YOLO11N: {
        const float* raw = static_cast<const float*>(engine->get_output(0));
        return postprocess_yolo11(raw, cfg.conf_threshold, cfg.iou_threshold);
    }

    case ModelType::YOLO26N: {
        const float* raw = static_cast<const float*>(engine->get_output(0));
        return postprocess_yolo26(raw, cfg.conf_threshold);
    }
    }

    return DetectionResult{};
}

// ═══════════════════════════════════════════════════════════════════════════
//  Inference task — pinned to Core 0
// ═══════════════════════════════════════════════════════════════════════════
static void inference_task(void* param) {
    auto* engine = static_cast<InferenceEngine*>(param);
    ModelConfig cfg = make_model_config(static_cast<ModelType>(ACTIVE_MODEL_TYPE),
                                        static_cast<EngineType>(ACTIVE_ENGINE_TYPE));

    // Determine if model requires float or int8 input
    bool needs_float = (cfg.type == ModelType::YOLO11N || cfg.type == ModelType::YOLO26N);

    ESP_LOGI(TAG, "═══════════════════════════════════════════════");
    ESP_LOGI(TAG, " Inference loop — modelo: %s", cfg.name);
    ESP_LOGI(TAG, " Engine:  %s", engine->runtime_name());
    ESP_LOGI(TAG, " Input:   %s", needs_float ? "float32" : "INT8");
    ESP_LOGI(TAG, " Core:    %d", xPortGetCoreID());
    ESP_LOGI(TAG, "═══════════════════════════════════════════════");

    while (true) {
        // ─── 1. Capture ──────────────────────────────────────────────
        metrics_frame_begin();

        camera_fb_t* fb = camera_capture();
        if (!fb) {
            ESP_LOGW(TAG, "Captura fallida, reintentando...");
            vTaskDelay(pdMS_TO_TICKS(100));
            continue;
        }

        // ─── 2. Preprocess ──────────────────────────────────────────
        esp_err_t ret;

        if (needs_float) {
            float* input_f = image_preprocess_float(fb);
            camera_release_fb(fb);
            metrics_preprocess_end();

            if (!input_f) {
                ESP_LOGW(TAG, "Preprocesamiento float fallido");
                continue;
            }

            // ─── 3. Inference ────────────────────────────────────────
            ret = engine->invoke_float(input_f);
        } else {
            int8_t* input_i = image_preprocess(fb);
            camera_release_fb(fb);
            metrics_preprocess_end();

            if (!input_i) {
                ESP_LOGW(TAG, "Preprocesamiento INT8 fallido");
                continue;
            }

            // ─── 3. Inference ────────────────────────────────────────
            ret = engine->invoke(input_i);
        }

        metrics_inference_end();

        if (ret != ESP_OK) {
            ESP_LOGE(TAG, "Inferencia fallida: %s", esp_err_to_name(ret));
            vTaskDelay(pdMS_TO_TICKS(500));
            continue;
        }

        // ─── 4. Postprocess ─────────────────────────────────────────
        DetectionResult dets = run_postprocess(engine, cfg);
        metrics_postprocess_end(dets.count);

        // ─── 5. Report ──────────────────────────────────────────────
        InferenceMetrics m = metrics_get();

        // Update arena usage
        m.arena_used = engine->get_arena_used();

        // Log every METRICS_REPORT_INTERVAL frames
        if (m.frame_id % METRICS_REPORT_INTERVAL == 0) {
            ESP_LOGI(TAG, "[#%lu] %s | %.1f ms (pre:%.1f inf:%.1f post:%.1f) | "
                          "%.1f FPS | %d dets | heap:%luK psram:%luK",
                     m.frame_id, cfg.name,
                     m.total_ms, m.preprocess_ms, m.inference_ms, m.postprocess_ms,
                     m.fps, dets.count,
                     m.heap_internal_free / 1024, m.psram_free / 1024);
        }

        // ─── 6. Broadcast to WebSocket ──────────────────────────────
        webserver_broadcast(m, dets);

        // Yield briefly so WDT is happy
        taskYIELD();
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  app_main — called by ESP-IDF on boot
// ═══════════════════════════════════════════════════════════════════════════
extern "C" void app_main(void) {
    ESP_LOGI(TAG, "═══════════════════════════════════════════════════════════");
    ESP_LOGI(TAG, " TFM TinyML Detector — ESP32-S3 Object Detection");
    ESP_LOGI(TAG, " Build: %s %s", __DATE__, __TIME__);
    ESP_LOGI(TAG, "═══════════════════════════════════════════════════════════");

    // ─── Print heap info ─────────────────────────────────────────────
    ESP_LOGI(TAG, "Heap interno libre: %lu KB",
             heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024);
    ESP_LOGI(TAG, "PSRAM libre:        %lu KB",
             heap_caps_get_free_size(MALLOC_CAP_SPIRAM) / 1024);

    // ─── 1. Init metrics ─────────────────────────────────────────────
    ESP_ERROR_CHECK(metrics_init());

    // ─── 2. Init camera ──────────────────────────────────────────────
    ESP_ERROR_CHECK(camera_init());

    // ─── 3. Init image preprocessing ─────────────────────────────────
    ESP_ERROR_CHECK(image_proc_init());

    // ─── 4. Init postprocessing ──────────────────────────────────────
    ESP_ERROR_CHECK(postprocess_init());

    // ─── 5. Create & init inference engine ───────────────────────────
    ModelConfig cfg = make_model_config(static_cast<ModelType>(ACTIVE_MODEL_TYPE),
                                        static_cast<EngineType>(ACTIVE_ENGINE_TYPE));

    ESP_LOGI(TAG, "Cargando modelo: %s (%s)",
             cfg.name, ACTIVE_ENGINE_TYPE == EngineType::TFLITE_MICRO
                       ? "TFLite Micro" : "ESP-DL");
    ESP_LOGI(TAG, "   TFLite size: %zu KB", cfg.tflite_size / 1024);
    ESP_LOGI(TAG, "   Arena estimado: %d KB", cfg.arena_size / 1024);

    InferenceEngine* engine = create_engine(static_cast<EngineType>(ACTIVE_ENGINE_TYPE));
    if (!engine) {
        ESP_LOGE(TAG, "No se pudo crear el motor de inferencia");
        return;
    }

    esp_err_t ret = engine->init(&cfg);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Error inicializando motor: %s", esp_err_to_name(ret));
        delete engine;
        return;
    }

    ESP_LOGI(TAG, "Arena usado: %zu KB", engine->get_arena_used() / 1024);

    // ─── 6. Start WiFi AP ────────────────────────────────────────────
    ESP_ERROR_CHECK(wifi_init_ap());

    // ─── 7. Start Web Server ─────────────────────────────────────────
    ESP_ERROR_CHECK(webserver_start());
    ESP_LOGI(TAG, "Dashboard: http://%s/", wifi_get_ip());

    // ─── 8. Launch inference task on Core 0 ──────────────────────────
    ESP_LOGI(TAG, "Lanzando tarea de inferencia en Core %d...", INFERENCE_TASK_CORE);

    BaseType_t task_ret = xTaskCreatePinnedToCore(
        inference_task,
        "inference",
        INFERENCE_TASK_STACK,
        engine,
        INFERENCE_TASK_PRIORITY,
        nullptr,
        INFERENCE_TASK_CORE
    );

    if (task_ret != pdPASS) {
        ESP_LOGE(TAG, "No se pudo crear la tarea de inferencia");
        engine->deinit();
        delete engine;
        return;
    }

    ESP_LOGI(TAG, "═══════════════════════════════════════════════════════════");
    ESP_LOGI(TAG, " ✅ Sistema iniciado correctamente");
    ESP_LOGI(TAG, " 📡 Conéctate a WiFi: %s / %s", WIFI_AP_SSID, WIFI_AP_PASS);
    ESP_LOGI(TAG, " 🌐 Dashboard: http://%s/", wifi_get_ip());
    ESP_LOGI(TAG, "═══════════════════════════════════════════════════════════");
}
